2021-10-25 08:04:24.102 | INFO     |  5684 | mycroft.messagebus.load_config:load_message_bus_config:33 | Loading message bus configs
2021-10-25 08:04:24.106 | INFO     |  5684 | mycroft_bus_client.client.client | Connected
2021-10-25 08:04:24.112 | INFO     |  5684 | mycroft.util.process_utils:start_message_bus_client:155 | Connected to messagebus
2021-10-25 08:04:24.116 | INFO     |  5684 | mycroft.skills.msm_wrapper:create_msm:96 | Acquiring lock to instantiate MSM
2021-10-25 08:04:28.077 | INFO     |  5684 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-25 08:04:28.575 | INFO     |  5684 | mycroft.skills.msm_wrapper:create_msm:112 | Releasing MSM instantiation lock.
2021-10-25 08:04:28.576 | INFO     |  5684 | mycroft.skills.skill_updater:_log_next_download_time:267 | Next scheduled skill update: 2021-10-25 08:04:27.575951
2021-10-25 08:04:28.576 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-pairing
2021-10-25 08:04:29.028 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:29.039 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-pairing
2021-10-25 08:04:29.039 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:29.041 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-pairing.mycroftai
2021-10-25 08:04:29.049 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-25 08:04:29.072 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-pairing.mycroftai
2021-10-25 08:04:29.078 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-25 08:04:29.079 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-pairing.mycroftai loaded successfully
2021-10-25 08:04:29.079 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-volume
2021-10-25 08:04:29.517 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:29.528 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-volume
2021-10-25 08:04:30.491 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-volume
2021-10-25 08:04:30.492 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:30.493 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-volume.mycroftai
2021-10-25 08:04:30.500 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-volume.mycroftai/settings.json
2021-10-25 08:04:30.609 | ERROR    |  5684 | VolumeSkill | Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]')
2021-10-25 08:04:33.624 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-volume.mycroftai
2021-10-25 08:04:33.626 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-volume.mycroftai/settings.json
2021-10-25 08:04:33.627 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-volume.mycroftai loaded successfully
2021-10-25 08:04:33.628 | INFO     |  5684 | __main__:on_started:177 | Skills service is starting up.
2021-10-25 08:04:33.682 | INFO     |  5684 | __main__:_update_system:154 | Attempting system update...
2021-10-25 08:04:36.905 | INFO     |  5684 | mycroft.enclosure.display_manager:_write_data:70 | Display Manager is creating /tmp/mycroft/ipc/managers/disp_info
2021-10-25 08:04:36.916 | INFO     |  5684 | __main__:_ensure_device_is_paired:133 | Device not paired, invoking the pairing skill
2021-10-25 08:04:36.941 | INFO     |  5684 | __main__:on_alive:181 | Skills service is alive.
2021-10-25 08:04:37.024 | INFO     |  5684 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-25 08:04:37.115 | INFO     |  5684 | PairingSkill | Communicating account URL to user
2021-10-25 08:04:37.583 | WARNING  |  5684 | msm.mycroft_skills_manager | No such default skill: mycroft-pandora
2021-10-25 08:04:37.584 | INFO     |  5684 | mycroft.skills.skill_manager:run:234 | Not all default skills are installed, performing skill update...
2021-10-25 08:04:37.584 | INFO     |  5684 | mycroft.skills.skill_updater:update_skills:149 | Beginning skill update...
2021-10-25 08:04:37.641 | INFO     |  5684 | msm.mycroft_skills_manager | building SkillEntry objects for all skills
2021-10-25 08:04:38.501 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:38.535 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-wolfram-alpha
2021-10-25 08:04:38.540 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-alarm
2021-10-25 08:04:38.546 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-date-time
2021-10-25 08:04:38.560 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-configuration
2021-10-25 08:04:38.576 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-unknown
2021-10-25 08:04:38.590 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-audio-record
2021-10-25 08:04:38.603 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-installer
2021-10-25 08:04:38.608 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-ip
2021-10-25 08:04:38.615 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-joke
2021-10-25 08:04:38.623 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/fallback-duckduckgo
2021-10-25 08:04:38.629 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-hello-world
2021-10-25 08:04:38.630 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-personal
2021-10-25 08:04:38.632 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-reminder
2021-10-25 08:04:38.632 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-singing
2021-10-25 08:04:38.633 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-playback-control
2021-10-25 08:04:38.680 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-npr-news
2021-10-25 08:04:38.681 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-naptime
2021-10-25 08:04:39.258 | ERROR    |  5684 | msm.mycroft_skills_manager | Error running install_or_update on homeassistant.mycroftai: MergeConflict
2021-10-25 08:04:39.259 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-speak
2021-10-25 08:04:39.821 | INFO     |  5684 | msm.skill_entry | Nothing new for mycroft-pairing
2021-10-25 08:04:39.891 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.089 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.093 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.121 | INFO     |  5684 | msm.skill_entry | Nothing new for mycroft-volume
2021-10-25 08:04:40.196 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-spelling
2021-10-25 08:04:40.205 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.255 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.261 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-personal
2021-10-25 08:04:40.263 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:40.267 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.267 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.268 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.288 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-stop
2021-10-25 08:04:40.292 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.295 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.298 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-playback-control
2021-10-25 08:04:40.319 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:40.333 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.354 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-audio-record
2021-10-25 08:04:40.361 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-support
2021-10-25 08:04:40.383 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.386 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-hello-world
2021-10-25 08:04:40.387 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:40.388 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/mycroft-timer
2021-10-25 08:04:40.389 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-naptime
2021-10-25 08:04:40.389 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:40.390 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-weather
2021-10-25 08:04:40.395 | INFO     |  5684 | msm.skill_entry | Successfully installed fallback-unknown
2021-10-25 08:04:40.395 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:40.397 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-version-checker
2021-10-25 08:04:40.437 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-volume
2021-10-25 08:04:40.522 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-speak
2021-10-25 08:04:40.523 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:40.524 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-fallback-duck-duck-go
2021-10-25 08:04:40.525 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-joke
2021-10-25 08:04:40.526 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/mycroftai/skill-wiki
2021-10-25 08:04:40.623 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.633 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-configuration
2021-10-25 08:04:40.646 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.753 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-installer
2021-10-25 08:04:40.755 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for fallback-wolfram-alpha
2021-10-25 08:04:40.817 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:40.895 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-ip
2021-10-25 08:04:40.965 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.027 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.063 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-date-time
2021-10-25 08:04:41.073 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-reminder
2021-10-25 08:04:41.073 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:41.075 | INFO     |  5684 | msm.skill_entry | Downloading skill: https://github.com/MycroftAI/skill-query
2021-10-25 08:04:41.221 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.244 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.254 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.327 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-npr-news
2021-10-25 08:04:41.373 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-alarm
2021-10-25 08:04:41.383 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-support-helper
2021-10-25 08:04:41.389 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.460 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-spelling
2021-10-25 08:04:41.461 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:41.473 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.594 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-version-checker
2021-10-25 08:04:41.595 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:41.631 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.708 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-wiki
2021-10-25 08:04:41.786 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.883 | INFO     |  5684 | msm.skill_entry | Successfully installed fallback-query
2021-10-25 08:04:41.884 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:41.941 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:41.975 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-timer
2021-10-25 08:04:41.975 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:42.062 | ERROR    |  5684 | msm.mycroft_skills_manager | Error running install_or_update on homeassistant: MergeConflict
2021-10-25 08:04:42.115 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:42.148 | INFO     |  5684 | msm.skill_entry | Installing requirements.txt for mycroft-weather
2021-10-25 08:04:42.228 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:42.262 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-stop
2021-10-25 08:04:42.263 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:42.921 | INFO     |  5684 | msm.skill_entry | Installing system requirements...
2021-10-25 08:04:42.936 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-singing
2021-10-25 08:04:42.936 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:43.149 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-audio-record
2021-10-25 08:04:43.149 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:45.097 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-fallback-duck-duck-go
2021-10-25 08:04:45.098 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:46.088 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-joke
2021-10-25 08:04:46.089 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:48.769 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-configuration
2021-10-25 08:04:48.769 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:49.677 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-installer
2021-10-25 08:04:49.677 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:53.675 | INFO     |  5684 | msm.skill_entry | Successfully installed fallback-wolfram-alpha
2021-10-25 08:04:53.675 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:04:54.637 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-ip
2021-10-25 08:04:54.638 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:07.461 | INFO     |  5684 | PairingSkill | Initiating device pairing sequence...
2021-10-25 08:05:07.461 | INFO     |  5684 | PairingSkill | Retrieving pairing code from device API...
2021-10-25 08:05:07.654 | INFO     |  5684 | PairingSkill | Pairing code obtained: TJY7RY
2021-10-25 08:05:07.654 | INFO     |  5684 | PairingSkill | Communicating pairing URL to user
2021-10-25 08:05:11.238 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-date-time
2021-10-25 08:05:11.239 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:14.407 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-npr-news
2021-10-25 08:05:14.408 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:15.373 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-alarm
2021-10-25 08:05:15.374 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:18.397 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-support-helper
2021-10-25 08:05:18.398 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:20.298 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-wiki
2021-10-25 08:05:20.299 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:21.398 | INFO     |  5684 | msm.skill_entry | Successfully installed mycroft-weather
2021-10-25 08:05:21.399 | INFO     |  5684 | msm.mycroft_skills_manager | invalidating skills cache
2021-10-25 08:05:21.450 | INFO     |  5684 | mycroft.skills.skill_updater:_log_next_download_time:267 | Next scheduled skill update: 2021-10-25 09:05:21.449848
2021-10-25 08:05:21.450 | INFO     |  5684 | mycroft.skills.skill_updater:update_skills:170 | Skill update complete
2021-10-25 08:05:21.451 | INFO     |  5684 | mycroft.skills.skill_manager:_load_on_startup:273 | Loading installed skills...
2021-10-25 08:05:21.452 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-ip.mycroftai
2021-10-25 08:05:21.491 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-ip.mycroftai/settings.json
2021-10-25 08:05:21.499 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-ip.mycroftai
2021-10-25 08:05:21.500 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-ip.mycroftai/settings.json
2021-10-25 08:05:21.501 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-ip.mycroftai loaded successfully
2021-10-25 08:05:21.501 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-reminder.mycroftai
2021-10-25 08:05:21.524 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-reminder.mycroftai/settings.json
2021-10-25 08:05:21.571 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-reminder.mycroftai
2021-10-25 08:05:21.576 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-reminder.mycroftai/settings.json
2021-10-25 08:05:21.586 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-reminder.mycroftai loaded successfully
2021-10-25 08:05:21.587 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-installer.mycroftai
2021-10-25 08:05:21.598 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-installer.mycroftai/settings.json
2021-10-25 08:05:21.631 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-installer.mycroftai
2021-10-25 08:05:21.632 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-installer.mycroftai/settings.json
2021-10-25 08:05:21.635 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-installer.mycroftai loaded successfully
2021-10-25 08:05:21.635 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-version-checker.mycroftai
2021-10-25 08:05:21.640 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
2021-10-25 08:05:21.674 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-version-checker.mycroftai
2021-10-25 08:05:21.675 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-version-checker.mycroftai/settings.json
2021-10-25 08:05:21.676 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-version-checker.mycroftai loaded successfully
2021-10-25 08:05:21.676 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-singing.mycroftai
2021-10-25 08:05:21.691 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-singing.mycroftai/settings.json
2021-10-25 08:05:21.709 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-singing.mycroftai
2021-10-25 08:05:21.710 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-singing.mycroftai/settings.json
2021-10-25 08:05:21.710 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-singing.mycroftai loaded successfully
2021-10-25 08:05:21.712 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-joke.mycroftai
2021-10-25 08:05:21.720 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-joke.mycroftai/settings.json
2021-10-25 08:05:21.733 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-joke.mycroftai
2021-10-25 08:05:21.734 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-joke.mycroftai/settings.json
2021-10-25 08:05:21.734 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-joke.mycroftai loaded successfully
2021-10-25 08:05:21.736 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-timer.mycroftai
2021-10-25 08:05:21.754 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-timer.mycroftai/settings.json
2021-10-25 08:05:21.791 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-timer.mycroftai
2021-10-25 08:05:21.792 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-timer.mycroftai/settings.json
2021-10-25 08:05:21.793 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-timer.mycroftai loaded successfully
2021-10-25 08:05:21.794 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: homeassistant.mycroftai
2021-10-25 08:05:22.169 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/homeassistant.mycroftai/settings.json
2021-10-25 08:05:22.170 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/homeassistant.mycroftai/settings.json
2021-10-25 08:05:22.238 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill homeassistant.mycroftai loaded successfully
2021-10-25 08:05:22.238 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-alarm.mycroftai
2021-10-25 08:05:22.306 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-alarm.mycroftai/settings.json
2021-10-25 08:05:22.306 | ERROR    |  5684 | AlarmSkill | Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]')
2021-10-25 08:05:22.417 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-alarm.mycroftai
2021-10-25 08:05:22.418 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-alarm.mycroftai/settings.json
2021-10-25 08:05:22.432 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-alarm.mycroftai loaded successfully
2021-10-25 08:05:22.433 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-naptime.mycroftai
2021-10-25 08:05:22.440 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-naptime.mycroftai/settings.json
2021-10-25 08:05:22.473 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-naptime.mycroftai
2021-10-25 08:05:22.474 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-naptime.mycroftai/settings.json
2021-10-25 08:05:22.474 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-naptime.mycroftai loaded successfully
2021-10-25 08:05:22.479 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-spelling.mycroftai
2021-10-25 08:05:22.489 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2021-10-25 08:05:22.512 | INFO     |  5684 | mycroft.skills.skill_loader:_check_for_first_run:324 | First run of mycroft-spelling.mycroftai
2021-10-25 08:05:22.512 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-spelling.mycroftai/settings.json
2021-10-25 08:05:22.521 | INFO     |  5684 | mycroft.skills.skill_loader:_communicate_load_status:344 | Skill mycroft-spelling.mycroftai loaded successfully
2021-10-25 08:05:22.522 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-fallback-duck-duck-go.mycroftai
2021-10-25 08:05:22.547 | ERROR    |  5684 | mycroft_bus_client.client.client | === ConnectionResetError(104, 'Connection reset by peer') ===
Traceback (most recent call last):
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 305, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 53, in read
    if not read_callback():
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 271, in read
    op_code, frame = self.sock.recv_data_frame(True)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-10-25 08:05:22.548 | ERROR    |  5684 | mycroft_bus_client.client.client | Exception closing websocket: ConnectionResetError(104, 'Connection reset by peer')
2021-10-25 08:05:22.548 | WARNING  |  5684 | mycroft_bus_client.client.client | Message Bus Client will reconnect in 5 seconds.
2021-10-25 08:05:22.554 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai/settings.json
2021-10-25 08:05:22.565 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-fallback-duck-duck-go.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.566 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-npr-news.mycroftai
2021-10-25 08:05:22.611 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-npr-news.mycroftai/settings.json
2021-10-25 08:05:22.619 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-npr-news.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.620 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-support-helper.mycroftai
2021-10-25 08:05:22.625 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-support-helper.mycroftai/settings.json
2021-10-25 08:05:22.630 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-support-helper.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 305, in _create_skill_instance
    self.instance._register_decorated()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 749, in _register_decorated
    self.register_intent(intent, method)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 985, in register_intent
    return self.register_intent_file(intent_parser, handler)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1022, in register_intent_file
    self.intent_service.register_padatious_intent(name, filename)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 129, in register_padatious_intent
    self.bus.emit(Message("padatious:register_intent", data))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.631 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-weather.mycroftai
2021-10-25 08:05:22.650 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-weather.mycroftai/settings.json
2021-10-25 08:05:22.663 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-weather.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.664 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-speak.mycroftai
2021-10-25 08:05:22.667 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-speak.mycroftai/settings.json
2021-10-25 08:05:22.673 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-speak.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.673 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-audio-record.mycroftai
2021-10-25 08:05:22.678 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2021-10-25 08:05:22.684 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-audio-record.mycroftai/settings.json
2021-10-25 08:05:22.684 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-audio-record.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.685 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-stop.mycroftai
2021-10-25 08:05:22.688 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-stop.mycroftai/settings.json
2021-10-25 08:05:22.693 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-stop.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.693 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-hello-world.mycroftai
2021-10-25 08:05:22.697 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-hello-world.mycroftai/settings.json
2021-10-25 08:05:22.702 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-hello-world.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:22.703 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-date-time.mycroftai
2021-10-25 08:05:23.008 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-date-time.mycroftai/settings.json
2021-10-25 08:05:23.015 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-date-time.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.016 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-configuration.mycroftai
2021-10-25 08:05:23.021 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-configuration.mycroftai/settings.json
2021-10-25 08:05:23.028 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-configuration.mycroftai/settings.json
2021-10-25 08:05:23.029 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-configuration.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.029 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-query.mycroftai
2021-10-25 08:05:23.034 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-query.mycroftai/settings.json
2021-10-25 08:05:23.038 | INFO     |  5684 | QuestionsAnswersSkill | Removing all handlers...
2021-10-25 08:05:23.038 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-query.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/fallback_skill.py", line 199, in default_shutdown
    super(FallbackSkill, self).default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.039 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-personal.mycroftai
2021-10-25 08:05:23.043 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-personal.mycroftai/settings.json
2021-10-25 08:05:23.048 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-personal.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 305, in _create_skill_instance
    self.instance._register_decorated()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 749, in _register_decorated
    self.register_intent(intent, method)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 985, in register_intent
    return self.register_intent_file(intent_parser, handler)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1022, in register_intent_file
    self.intent_service.register_padatious_intent(name, filename)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 129, in register_padatious_intent
    self.bus.emit(Message("padatious:register_intent", data))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.048 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-wolfram-alpha.mycroftai
2021-10-25 08:05:23.076 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-wolfram-alpha.mycroftai/settings.json
2021-10-25 08:05:23.087 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-wolfram-alpha.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.087 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-wiki.mycroftai
2021-10-25 08:05:23.093 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-wiki.mycroftai/settings.json
2021-10-25 08:05:23.098 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-wiki.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.098 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: fallback-unknown.mycroftai
2021-10-25 08:05:23.102 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/fallback-unknown.mycroftai/settings.json
2021-10-25 08:05:23.108 | INFO     |  5684 | UnknownSkill | Removing all handlers...
2021-10-25 08:05:23.108 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/fallback-unknown.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/fallback_skill.py", line 199, in default_shutdown
    super(FallbackSkill, self).default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.109 | INFO     |  5684 | mycroft.skills.skill_loader:load:185 | ATTEMPTING TO LOAD SKILL: mycroft-playback-control.mycroftai
2021-10-25 08:05:23.114 | INFO     |  5684 | mycroft.skills.settings:get_local_settings:83 | /opt/mycroft/skills/mycroft-playback-control.mycroftai/settings.json
2021-10-25 08:05:23.120 | ERROR    |  5684 | mycroft.skills.skill_manager:_load_skill:305 | Load of skill /opt/mycroft/skills/mycroft-playback-control.mycroftai failed!
Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 302, in _create_skill_instance
    self.instance.load_data_files()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1274, in load_data_files
    self.load_vocab_files(root_directory)
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1300, in load_vocab_files
    aliases)
  File "/opt/mycroft-core/mycroft/skills/intent_service_interface.py", line 56, in register_adapt_keyword
    {**entity_data, **compatibility_data})
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft-core/mycroft/skills/skill_manager.py", line 303, in _load_skill
    load_status = skill_loader.load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 186, in load
    return self._load()
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 244, in _load
    if skill_module and self._create_skill_instance(skill_module):
  File "/opt/mycroft-core/mycroft/skills/skill_loader.py", line 310, in _create_skill_instance
    self.instance.default_shutdown()
  File "/opt/mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1374, in default_shutdown
    self.gui.shutdown()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 376, in shutdown
    self.release()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 366, in release
    self.clear()
  File "/opt/mycroft-core/mycroft/enclosure/gui.py", line 130, in clear
    {"__from": self.skill.skill_id}))
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/mycroft_bus_client/client/client.py", line 160, in emit
    self.client.send(message.serialize())
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 250, in send
    return self.send_frame(frame)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 275, in send_frame
    l = self._send(data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_core.py", line 445, in _send
    return send(self.sock, data)
  File "/opt/mycroft-core/.venv/lib/python3.7/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2021-10-25 08:05:23.120 | INFO     |  5684 | mycroft.skills.skill_manager:_load_on_startup:275 | Skills all loaded!
2021-10-25 08:05:27.555 | INFO     |  5684 | mycroft_bus_client.client.client | Connected
2021-10-25 08:05:38.028 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-pairing.mycroftai/settings.json
2021-10-25 08:05:38.329 | INFO     |  5684 | mycroft.skills.settings:save_settings:116 | Skill settings successfully saved to /home/runner/.config/mycroft/skills/mycroft-timer.mycroftai/settings.json
